name: Studio Matteo Feriotti
favicon: null
layout_spectrum: 0.718805770156905
typography_spectrum: 0.752610003342852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6292949030175805
  lightness: 0.18435223354026675
  saturation: 0.6464306360576302
  rhythmicContrast: 0.1450907769612968
purpose: []
